### ISSUE TITLE
snarky-js dependency conflict

### ISSUE THREAD

**Issue by marekyggdrasil** [octaborg/prototype#5]
## Context

I find a problem of importing a module that imports `snarky-js`. I suspect there might be conflict if imported module also imports `snarky-js`.

## What happens

We developed [octa-types](https://github.com/octaborg/octa-types/tree/5b4294fa0ede43a5b0ed37030a114915ab127dc8) module to share some code between our codebases. Then I import it in the [transaction-data-repository](https://github.com/octaborg/prototype/tree/8ef313da57958c73453f4d7246336d2774a4b6a3/transaction-data-repository) and if I attempt to use `snarky-js` types in both modules (importend one `octa-types` and one that imports `transaction-data-repository`) I get the following error.

```bash
[nodemon] restarting due to changes...
[nodemon] starting `node --no-warnings --experimental-specifier-resolution=node --loader ts-node/esm src/server.ts`
/Users/marek/Development/octa/prototype/transaction-data-repository/node_modules/ts-node/src/index.ts:750
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/models/octa.ts:20:17 - error TS2345: Argument of type 'import("/Users/marek/Development/octa/prototype/transaction-data-repository/node_modules/snarkyjs/dist/server/snarky").Field' is not assignable to parameter of type 'import("/Users/marek/Development/octa/octa-types/node_modules/snarkyjs/dist/server/snarky").Field'.
  Types of property 'add' are incompatible.
    Type '(y: string | number | boolean | import("/Users/marek/Development/octa/prototype/transaction-data-repository/node_modules/snarkyjs/dist/server/snarky").Field) => import("/Users/marek/Development/octa/prototype/transaction-data-repository/node_modules/snarkyjs/dist/server/snarky").Field' is not assignable to type '(y: string | number | boolean | import("/Users/marek/Development/octa/octa-types/node_modules/snarkyjs/dist/server/snarky").Field) => import("/Users/marek/Development/octa/octa-types/node_modules/snarkyjs/dist/server/snarky").Field'.
      Types of parameters 'y' and 'y' are incompatible.
        Type 'string | number | boolean | import("/Users/marek/Development/octa/octa-types/node_modules/snarkyjs/dist/server/snarky").Field' is not assignable to type 'string | number | boolean | import("/Users/marek/Development/octa/prototype/transaction-data-repository/node_modules/snarkyjs/dist/server/snarky").Field'.
          Type 'Field' is not assignable to type 'string | number | boolean | Field'.
            Type 'import("/Users/marek/Development/octa/octa-types/node_modules/snarkyjs/dist/server/snarky").Field' is not assignable to type 'import("/Users/marek/Development/octa/prototype/transaction-data-repository/node_modules/snarkyjs/dist/server/snarky").Field'.
              The types returned by 'toJSON()' are incompatible between these types.
                Type 'import("/Users/marek/Development/octa/octa-types/node_modules/snarkyjs/dist/server/snarky").JSONValue' is not assignable to type 'import("/Users/marek/Development/octa/prototype/transaction-data-repository/node_modules/snarkyjs/dist/server/snarky").JSONValue'.
                  Type 'JSON[]' is not assignable to type 'JSONValue'.
                    Type 'JSON[]' is not assignable to type 'JSONValue[]'.
                      Type 'JSON' is not assignable to type 'JSONValue'.
                        Type 'JSON' is not assignable to type '{ [key: string]: JSONValue; }'.
                          Index signature for type 'string' is missing in type 'JSON'.

20                 new Field(1),
                   ~~~~~~~~~~~~
src/models/octa.ts:23:21 - error TS2345: Argument of type 'import("/Users/marek/Development/octa/prototype/transaction-data-repository/node_modules/snarkyjs/dist/server/snarky").Bool' is not assignable to parameter of type 'import("/Users/marek/Development/octa/octa-types/node_modules/snarkyjs/dist/server/snarky").Bool'.
  Type 'Bool' is missing the following properties from type 'Bool': isTrue, isFalse

23                     new Bool(true),
                       ~~~~~~~~~~~~~~
src/models/octa.ts:33:9 - error TS2345: Argument of type 'import("/Users/marek/Development/octa/prototype/transaction-data-repository/node_modules/snarkyjs/dist/server/snarky").Field' is not assignable to parameter of type 'import("/Users/marek/Development/octa/octa-types/node_modules/snarkyjs/dist/server/snarky").Field'.

33         new Field(1),
           ~~~~~~~~~~~~

    at createTSError (/Users/marek/Development/octa/prototype/transaction-data-repository/node_modules/ts-node/src/index.ts:750:12)
    at reportTSError (/Users/marek/Development/octa/prototype/transaction-data-repository/node_modules/ts-node/src/index.ts:754:19)
    at getOutput (/Users/marek/Development/octa/prototype/transaction-data-repository/node_modules/ts-node/src/index.ts:941:36)
    at Object.compile (/Users/marek/Development/octa/prototype/transaction-data-repository/node_modules/ts-node/src/index.ts:1243:30)
    at /Users/marek/Development/octa/prototype/transaction-data-repository/node_modules/ts-node/src/esm.ts:282:37
    at Generator.next (<anonymous>)
    at /Users/marek/Development/octa/prototype/transaction-data-repository/node_modules/ts-node/dist/esm.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/marek/Development/octa/prototype/transaction-data-repository/node_modules/ts-node/dist/esm.js:4:12)
    at transformSource (/Users/marek/Development/octa/prototype/transaction-data-repository/node_modules/ts-node/dist/esm.js:127:16) {
  diagnosticText: `\x1B[96msrc/models/octa.ts\x1B[0m:\x1B[93m20\x1B[0m:\x1B[93m17\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2345: \x1B[0mArgument of type 'import("/Users/marek/Development/octa/prototype/transaction-data-repository/node_modules/snarkyjs/dist/server/snarky").Field' is not assignable to parameter of type 'import("/Users/marek/Development/octa/octa-types/node_modules/snarkyjs/dist/server/snarky").Field'.\n` +
    "  Types of property 'add' are incompatible.\n" +
    `    Type '(y: string | number | boolean | import("/Users/marek/Development/octa/prototype/transaction-data-repository/node_modules/snarkyjs/dist/server/snarky").Field) => import("/Users/marek/Development/octa/prototype/transaction-data-repository/node_modules/snarkyjs/dist/server/snarky").Field' is not assignable to type '(y: string | number | boolean | import("/Users/marek/Development/octa/octa-types/node_modules/snarkyjs/dist/server/snarky").Field) => import("/Users/marek/Development/octa/octa-types/node_modules/snarkyjs/dist/server/snarky").Field'.\n` +
    "      Types of parameters 'y' and 'y' are incompatible.\n" +
    `        Type 'string | number | boolean | import("/Users/marek/Development/octa/octa-types/node_modules/snarkyjs/dist/server/snarky").Field' is not assignable to type 'string | number | boolean | import("/Users/marek/Development/octa/prototype/transaction-data-repository/node_modules/snarkyjs/dist/server/snarky").Field'.\n` +
    "          Type 'Field' is not assignable to type 'string | number | boolean | Field'.\n" +
    `            Type 'import("/Users/marek/Development/octa/octa-types/node_modules/snarkyjs/dist/server/snarky").Field' is not assignable to type 'import("/Users/marek/Development/octa/prototype/transaction-data-repository/node_modules/snarkyjs/dist/server/snarky").Field'.\n` +
    "              The types returned by 'toJSON()' are incompatible between these types.\n" +
    `                Type 'import("/Users/marek/Development/octa/octa-types/node_modules/snarkyjs/dist/server/snarky").JSONValue' is not assignable to type 'import("/Users/marek/Development/octa/prototype/transaction-data-repository/node_modules/snarkyjs/dist/server/snarky").JSONValue'.\n` +
    "                  Type 'JSON[]' is not assignable to type 'JSONValue'.\n" +
    "                    Type 'JSON[]' is not assignable to type 'JSONValue[]'.\n" +
    "                      Type 'JSON' is not assignable to type 'JSONValue'.\n" +
    "                        Type 'JSON' is not assignable to type '{ [key: string]: JSONValue; }'.\n" +
    "                          Index signature for type 'string' is missing in type 'JSON'.\n" +
    '\n' +
    '\x1B[7m20\x1B[0m                 new Field(1),\n' +
    '\x1B[7m  \x1B[0m \x1B[91m                ~~~~~~~~~~~~\x1B[0m\n' +
    `\x1B[96msrc/models/octa.ts\x1B[0m:\x1B[93m23\x1B[0m:\x1B[93m21\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2345: \x1B[0mArgument of type 'import("/Users/marek/Development/octa/prototype/transaction-data-repository/node_modules/snarkyjs/dist/server/snarky").Bool' is not assignable to parameter of type 'import("/Users/marek/Development/octa/octa-types/node_modules/snarkyjs/dist/server/snarky").Bool'.\n` +
    "  Type 'Bool' is missing the following properties from type 'Bool': isTrue, isFalse\n" +
    '\n' +
    '\x1B[7m23\x1B[0m                     new Bool(true),\n' +
    '\x1B[7m  \x1B[0m \x1B[91m                    ~~~~~~~~~~~~~~\x1B[0m\n' +
    `\x1B[96msrc/models/octa.ts\x1B[0m:\x1B[93m33\x1B[0m:\x1B[93m9\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2345: \x1B[0mArgument of type 'import("/Users/marek/Development/octa/prototype/transaction-data-repository/node_modules/snarkyjs/dist/server/snarky").Field' is not assignable to parameter of type 'import("/Users/marek/Development/octa/octa-types/node_modules/snarkyjs/dist/server/snarky").Field'.\n` +
    '\n' +
    '\x1B[7m33\x1B[0m         new Field(1),\n' +
    '\x1B[7m  \x1B[0m \x1B[91m        ~~~~~~~~~~~~\x1B[0m\n',
  diagnosticCodes: [ 2345, 2345, 2345 ]
}
[nodemon] app crashed - waiting for file changes before starting...
```

## How to reproduce

1. Clone [octa-types](https://github.com/octaborg/octa-types/tree/5b4294fa0ede43a5b0ed37030a114915ab127dc8)
2. In the `octa-types` directory run `npm install` then `npm run prepare` then `npm build`.
3. Clone [prototype](https://github.com/octaborg/prototype/tree/8ef313da57958c73453f4d7246336d2774a4b6a3) and change directory to `transaction-data-repository`.
4. Run `npm install` and just to be sure, also `npm link /path/to/octa-types` and `npm install /path/to/octa-types`.
5. Then execute `npm run dev`
6. You should get the error above

## Other observations

If there is no usage of `snarky-js` types in the `transaction-data-repository` (no instantiation of `Field`, `Bool` etc) then everything runs.

**Comment by marekyggdrasil** [comment]
Gregor found version mismatch. Fixed in https://github.com/octaborg/octa-types/commit/3b5bddf132f371055fd521d0aa351f409ed6a5a9 closing
